Repository neoforged/GradleUtils, pull requests merged in 2023-12, with the labels that each got.

#14 Add GDI
  build.gradle
  gradle.properties
  src/main/groovy/net/neoforged/gradleutils/GradleUtilsExtension.groovy
  src/main/groovy/net/neoforged/gradleutils/specs/VersionBranchesSpec.groovy
  src/main/groovy/net/neoforged/gradleutils/specs/VersionSpec.groovy
  src/main/groovy/net/neoforged/gradleutils/specs/VersionTagsSpec.groovy
Labels: enhancement

#15 Fix project not being correctly passed down to `signAllPublications`
  build.gradle
  src/main/groovy/net/neoforged/gradleutils/GradleUtilsExtension.groovy
Labels: bug

#13 Improve the error message when there are no Git tags
  build.gradle
  src/main/groovy/net/neoforged/gradleutils/VersionCalculator.groovy
Labels: bug, enhancement

#16 Implement a report of all published Maven publications
  build.gradle
  src/main/groovy/net/neoforged/gradleutils/GradleUtilsExtension.groovy
  src/main/groovy/net/neoforged/gradleutils/ReportMavenPublications.groovy
Labels: enhancement

#17 Add PR publishing workflow generation
  build.gradle
  src/actionsTemplate/resources/.github/workflows/publish-prs.yml
  src/main/groovy/net/neoforged/gradleutils/tasks/CIConfigExtractionTask.java
  src/main/groovy/net/neoforged/gradleutils/tasks/ExtractActionsWorkflowsTask.java
Labels: enhancement
